# Generated by Django 6.0.2 on 2026-02-25 17:32

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backupcode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='backupcode',
            name='accounts_ba_user_id_e8f283_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=accounts.fields.EncryptedCharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='BackupCode',
        ),
    ]
