# Generated by Django 6.0.2 on 2026-02-26 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_add_default_currencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recurringtransfer',
            index=models.Index(fields=['next_transfer_date'], name='banking_rec_next_tr_05e4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'created_at'], name='banking_tra_account_f152f8_idx'),
        ),
    ]
