# Generated by Django 6.0.2 on 2026-02-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
