from django.urls import path
from .views import (
    AccountListAPIView,
    RecentTransactionListAPIView,
    RecurringTransferListCreateAPIView,
    RecurringTransferDetailAPIView,
    StatementAPIView,
    StatementPDFAPIView,
    GatewayChargeAPIView,
    TransactionSearchAPIView,
    StatementExportAPIView,
    BankingStatsAPIView,
    open_account_view,
    account_detail_view,
    deposit_view,
    withdraw_view,
    transfer_view,
    close_account_view,
    tag_transaction_view,
    transaction_pdf_view,
    cancel_recurring_view,
)

urlpatterns = [
    path('accounts/', AccountListAPIView.as_view(), name='account-list'),
    path('accounts/open/', open_account_view, name='open-account'),
    path('accounts/<int:pk>/', account_detail_view, name='account-detail'),
    path('accounts/<int:pk>/deposit/', deposit_view, name='deposit'),
    path('transactions/<int:pk>/tag/', tag_transaction_view, name='tag-transaction'),
    path('transactions/<int:pk>/pdf/', transaction_pdf_view, name='transaction-pdf'),
    path('accounts/<int:pk>/withdraw/', withdraw_view, name='withdraw'),
    path('accounts/<int:pk>/transfer/', transfer_view, name='transfer'),
    path('accounts/<int:pk>/close/', close_account_view, name='close-account'),
    path('transactions/recent/', RecentTransactionListAPIView.as_view(), name='recent-transactions'),
    path('recurring-transfers/', RecurringTransferListCreateAPIView.as_view(), name='recurring-list'),
    path('recurring-transfers/<int:pk>/', RecurringTransferDetailAPIView.as_view(), name='recurring-detail'),
    path('statements/', StatementAPIView.as_view(), name='statements'),
    path('transactions/search/', TransactionSearchAPIView.as_view(), name='transaction-search'),
    path('statements/export/', StatementExportAPIView.as_view(), name='statement-export'),
    path('statements/pdf/', StatementPDFAPIView.as_view(), name='statement-pdf'),
    path('payments/charge/', GatewayChargeAPIView.as_view(), name='gateway-charge'),
    path('stats/', BankingStatsAPIView.as_view(), name='bank-stats'),
    path('recurring-transfers/<int:pk>/cancel/', cancel_recurring_view, name='cancel-recurring'),
]